Add free-list support to ArrayStore
vespa-engine/vespa pull request #10288
Opened 2019-08-15 10:38 UTC by vekterli

@geirst @toregge please review very carefully 🙂

* Add support for enabling freelists via `ArrayStoreConfig`. Currently defaults to false.
* Small array allocations from freelist reuse both entry ref and array buffer
* Large array allocations from freelist reuse entry ref only

2019-08-15 13:10 UTC, toregge requested changes
Please use FreeListAllocator for large arrays, with fixup afterwards for extra bytes used.

2019-08-16 09:00 UTC, vekterli commented on vespalib/src/vespa/vespalib/datastore/array_store.hpp
> +    return ref;
Addressed in rebased commit

2019-08-16 09:01 UTC, vekterli commented
@geirst @toregge PTAL. Implementation now simplified in terms of `FreeListAllocator` and with explicitly added tracking of extra space used

2019-08-16 09:07 UTC, geirst approved these changes
👍

2019-08-16 09:17 UTC, toregge approved these changes

2019-08-16 10:30 UTC, merged