Initial tenant cost API that is not wired up to any clients yet
vespa-engine/vespa pull request #10906
Opened 2019-10-07 13:58 UTC by oyving

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2019-10-07 13:58 UTC, oyving commented
FYI - @olaaun

2019-10-08 07:27 UTC, mpolden requested changes

2019-10-08 07:27 UTC, mpolden commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/restapi/application/ApplicationApiHandler.java
> +            return Optional.empty();
It's better to just rethrow this as an `IllegalArgumentExeption` and remove the explicit `month.isEmpty()` check, the `handle` method will then convert this into a bad request response.

2019-10-08 07:27 UTC, mpolden commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/restapi/application/ApplicationApiHandler.java
> +    private Optional<LocalDate> tenantCostParseMonth(String monthString) {
Looks like this is actually parsing a date string, not just month?

2019-10-08 08:06 UTC, mpolden reviewed
There's a test failure:
```
[ERROR] Failures: 
[ERROR]   PathGroupTest.uniqueMatches:48 Paths '/application/v4/tenant/{tenant}/cost' and '/application/v4/tenant/{tenant}/cost/{*}' overlap.
```

2019-10-08 08:06 UTC, mpolden commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/restapi/application/ApplicationApiHandler.java
> +        if (path.matches("/application/v4/tenant/{tenant}/cost/{month}")) return tenantCost(path.get("tenant"), path.get("month"), request);
Path parameter should be renamed.

2019-10-08 11:38 UTC, mpolden approved these changes

2019-10-08 11:39 UTC, merged