Reapply "Validate register and refresh""
vespa-engine/vespa pull request #11158
Opened 2019-10-30 13:42 UTC by tokle

Reverts vespa-engine/vespa#11157

2019-10-30 15:12 UTC, mpolden approved these changes

2019-10-30 16:28 UTC, bjorncs requested changes

2019-10-31 08:03 UTC, tokle commented on athenz-identity-provider-service/src/main/java/com/yahoo/vespa/hosted/athenz/instanceproviderservice/instanceconfirmation/InstanceValidator.java
> +        this(keyProvider, superModelProvider, nodeRepository, new IdentityDocumentSigner(), new AthenzService(config.domain(), "tenant"));
😢

2019-10-31 10:02 UTC, bjorncs approved these changes

2019-10-31 10:03 UTC, merged