Setting default application Id values in _meta
vespa-engine/vespa pull request #12182
Opened 2020-02-13 14:24 UTC by bjormel

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-02-13 14:28 UTC, bjormel commented
@arnej27959 would something like this work? 

The goal is to allow tenants to avoid having to maintain application specific information in their Splunk log forwarding apps.
With _meta specified in /opt/splunkforwarder/etc/system/local/inputs.conf this will be applied unless the customer has overridden -meta in their app.

2020-02-13 14:31 UTC, bjormel commented
https://git.ouroath.com/vespa/vespa-yahoo/pull/3618 to set the application id info as env variables in docker.

Current env variables:
`US-WEST-1 [bjormel@le04555:~]$ sudo docker exec le04555-v6-11  env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/y/bin:/home/y/sbin
HOSTNAME=le04555-v6-11.ostk.bm2.prod.gq1.yahoo.com
TERM=xterm
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_ALL=en_US.UTF-8
HOME=/root`

2020-02-14 11:46 UTC, bjormel commented
The environment values are now available in CD:
`CD-US-CENTRAL-1 [root@17491290-v6-2:/]$ xargs --null --max-args=1 < /proc/$(pgrep vespa-runserver | head -1)/environ | grep -E "VESPA_(TENANT|APPLICATION|INSTANCE)"`
`VESPA_INSTANCE=default`
`VESPA_TENANT=vespa`
`VESPA_APPLICATION=canary-pipeline`

2020-02-14 12:01 UTC, arnej27959 requested changes
will push a commit fixing so it compiles...

2020-02-14 12:01 UTC, arnej27959 commented on logforwarder/src/apps/vespa-logforwarder-start/cf-handler.cpp
> +    fprintf(fp, "_meta = vespa_tenant::%s vespa_application::%s vespa_instance::%s\n", getenv("VESPA_TENANT"), getenv("VESPA_APPLICTAION"), getenv("VESPA_INSTANCE"));
must be VESPA_APPLICATION here.
also, we should probably detect if any of these are unset (getenv returns null pointer), i guess...

2020-02-14 12:33 UTC, bjormel commented
@arnej27959 sorry, did not notice that you had fixed the typos, and ended up doing the change without pulling first, causing a mess.

Should I create a new branch/PR?

2020-02-14 13:18 UTC, arnej27959 approved these changes
looks better now :-)

2020-02-14 13:23 UTC, merged