Ensure content is consumed to allow connection reuse
vespa-engine/vespa pull request #14622
Opened 2020-09-29 15:50 UTC by bjorncs

FYI @baldersheim 

I'll do more fixes in upcoming PR

2020-09-29 20:24 UTC, baldersheim requested changes
Unit test failure
 IOThreadTest.testPollingOldConnections:107 expected:<1> but was:<0>

2020-09-30 08:08 UTC, bjorncs commented
@baldersheim @tokle PTAL

2020-09-30 08:32 UTC, tokle commented on vespa-http-client/src/test/java/com/yahoo/vespa/http/client/core/communication/IOThreadTest.java
> +        tester.clock().advance(Duration.ofSeconds(31)); // Default connection ttl is 15
update comment?

2020-09-30 08:38 UTC, tokle approved these changes

2020-09-30 08:40 UTC, merged