Support references in concrete document types
vespa-engine/vespa pull request #1723
Opened 2017-02-08 16:04 UTC by vekterli

@geirst @bjorncs Please review

2017-02-08 18:26 UTC, bjorncs approved these changes

2017-02-08 18:27 UTC, bjorncs requested changes
See comment

2017-02-09 10:11 UTC, bjorncs approved these changes

2017-02-09 10:17 UTC, geirst reviewed
Overall looks good, please consider my comment

2017-02-09 11:35 UTC, geirst approved these changes
👍

2017-02-09 11:52 UTC, merged