rename job
vespa-engine/vespa pull request #17643
Opened 2021-04-28 14:40 UTC by kkraune

- with this, we can display a useful job name in the badge on the overview page

2021-04-28 17:22 UTC, bratseth approved these changes

2021-04-28 21:53 UTC, aressem approved these changes

2021-04-28 21:53 UTC, aressem commented
16:43:07 $ echo 'Error: Cache is set for non-existing job: main'; exit 1
16:43:07 Error: Cache is set for non-existing job: main

2021-04-28 21:53 UTC, aressem requested changes
16:43:07 $ echo 'Error: Cache is set for non-existing job: main'; exit 1
16:43:07 Error: Cache is set for non-existing job: main

2021-04-29 07:54 UTC, kkraune commented
@aressem I _think_ the build failure now is something else, OK to merge?

2021-04-29 08:02 UTC, aressem approved these changes

2021-04-29 08:02 UTC, merged