Use AbstractUtf8Array in interface and a more flexible implementation…
vespa-engine/vespa pull request #17786
Opened 2021-05-07 20:06 UTC by baldersheim

… to reduce amount of copying.

@hmusum PR

2021-05-07 20:43 UTC, hmusum requested changes
Looks good to me, but some unit tests fail

2021-05-07 21:22 UTC, baldersheim commented
I think it is OK now, but I want to refactor the ByteWriter test and also use that for the Utf8ByteWriter first. o will hold for now.

2021-05-08 04:52 UTC, hmusum commented
Fails one unit test (where config is empty)

2021-05-09 05:00 UTC, hmusum approved these changes

2021-05-09 08:22 UTC, merged