Use external rank expressions, gated by feature flag.
vespa-engine/vespa pull request #17954
Opened 2021-05-24 19:23 UTC by baldersheim

@hmusum or @bratseth or @lesters PR
@havardpe FYI

2021-05-24 20:11 UTC, bratseth approved these changes

2021-05-24 20:14 UTC, hmusum requested changes
Two suggestions, one is necessary to implement interface correctly. Otherwise LGTM

2021-05-24 20:14 UTC, hmusum commented on configserver/src/main/java/com/yahoo/vespa/config/server/deploy/ModelContextImpl.java
> +        @Override public boolean isUseExternalRankExpression() { return useExternalRankExpression; }
```suggestion
        @Override public boolean useExternalRankExpressions() { return useExternalRankExpression; }
```

2021-05-24 20:14 UTC, hmusum commented on flags/src/main/java/com/yahoo/vespa/flags/Flags.java
> +            "Wheter to use distributed external rank expression or inline in rankproperties",
```suggestion
            "Whether to use distributed external rank expression or inline in rankproperties",
```

2021-05-25 04:43 UTC, hmusum approved these changes

2021-05-25 12:44 UTC, hmusum approved these changes

2021-05-25 13:05 UTC, merged