WIP - api for granting support access and registering granted certifi…
vespa-engine/vespa pull request #17987
Opened 2021-05-26 12:14 UTC by andreer

…cates

2021-05-26 14:57 UTC, andreer commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/support_access/SupportAccessControl.java
> +    public SupportAccess registerGrant(DeploymentId deployment, String by, X509Certificate certificate) {
Unused - will be used by @tokle

2021-05-27 09:25 UTC, oyving requested changes
Some copyright notices are missing on the new files. A package should probably be renamed. Some missing javadoc.

2021-05-27 09:25 UTC, oyving commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/support_access/SupportAccess.java
> +package com.yahoo.vespa.hosted.controller.support_access;
Also, copyright notice

2021-05-27 09:25 UTC, oyving commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/support_access/SupportAccess.java
> +public class SupportAccess {
Javadoc. Should say if it's immutable or not.

2021-05-27 09:25 UTC, oyving commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/support_access/SupportAccess.java
> +        this.grantHistory = grantHistory;
If `SupportAccess` is immutable, these lists should be immutable as well. Either here or in the getters exposing them.

2021-05-27 09:25 UTC, oyving commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/support_access/SupportAccessChange.java
> +public class SupportAccessChange {
javadoc and copyright

2021-05-27 09:25 UTC, oyving commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/support_access/SupportAccessControl.java
> +package com.yahoo.vespa.hosted.controller.support_access;
copyright

2021-05-27 11:59 UTC, oyving approved these changes

2021-05-28 05:42 UTC, merged