Detect that we are running in docker-on-mac and automatically reduce …
vespa-engine/vespa pull request #21590
Opened 2022-03-08 08:56 UTC by baldersheim

…timer frequency due to expensive

calls to sample time. This might reduce timeout accuracy from 1ms to 10ms, but that is fine for development.
docker-on-mac will never be supported as production environment.

@arnej27959 and @hmusum PR
@jobergum FYI

2022-03-08 09:28 UTC, arnej27959 requested changes
we can not echo to stdout here; it will appear as output from things like vespa-visit.  Use ":" not "echo".

2022-03-08 10:45 UTC, baldersheim commented
@arnej27959 echo removed. PTAL

2022-03-08 11:52 UTC, arnej27959 approved these changes
looks good to me

2022-03-08 21:58 UTC, merged

2022-03-09 08:10 UTC, jobergum commented
💯 🥇