Jonmv/multi range item 2
vespa-engine/vespa pull request #21773
Opened 2022-03-22 21:12 UTC by jonmv

@baldersheim please review. #19218 for context.

2022-03-23 06:58 UTC, jonmv commented
Need to prune e.g., (1, 1), when [0, 1) is already present. That isn't handled now, as these two do not overlap.

2022-04-05 10:00 UTC, baldersheim requested changes
See my comments. Overall this looks good.

But if you want to bundle api and encoding then this will not be usable for a long time.
This introduces 2 indexes with a term and that is a new concept that does not exist in the backend. Adding support for this will take quite some effort.

I would probably serialize as today as a first step. Then they would get the benefit and you would get feedback if the API is suitable.

2022-10-25 11:26 UTC, jonmv commented on container-search/src/main/java/com/yahoo/prelude/query/MultiRangeItem.java
> +        buffer.put(metadata);
Added type argument, with support for int, long and double.
Also added dynamic selection of integer compression, which can be extended later.

2022-10-25 11:26 UTC, jonmv commented on container-search/src/main/java/com/yahoo/prelude/query/MultiRangeItem.java
> +            buffer.putDouble(range.start.doubleValue());
Done.

2022-10-25 11:28 UTC, jonmv commented on container-search/src/main/java/com/yahoo/prelude/query/MultiRangeItem.java
> +    public void setIndexName(String index) { } // This makes no sense :<
Yes ...

2022-10-25 11:28 UTC, jonmv commented
PTAL.

2023-01-08 10:33 UTC, baldersheim approved these changes

2023-01-08 10:33 UTC, merged