Add best-of-random-2 dispatch policy.
vespa-engine/vespa pull request #23727
Opened 2022-08-19 17:33 UTC by baldersheim

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-08-21 14:02 UTC, baldersheim commented
@bratseth PR

2022-08-22 07:11 UTC, bratseth requested changes
LoadBalancer.Policy, and the switch in the LoadBalancer constructor is missing "adaptive". Otherwise LGTM!

2022-08-22 07:27 UTC, baldersheim commented on config-model/src/main/resources/schema/content.rnc
> +    element dispatch-policy { string "round-robin" | string "adaptive" | string "random" | "best-of-random-2" | "latency-amortized-over-requests" }? &
I intentionally left it out here as I am not sure it is needed, and wanted to avoid its use until I do.

2022-08-22 07:30 UTC, baldersheim commented
LoadBalancer.Policy does not have ADAPTIVE as that means whatever vespa thinks is the best default. Currently that is a synonym for latency-amortized-over-requests, which is fairly technical.

2022-08-22 07:31 UTC, merged