switch to new implementation of start-cbinaries.sh
vespa-engine/vespa pull request #24274
Opened 2022-09-30 11:34 UTC by arnej27959

@baldersheim please review
I think we can give this a try on factory.
@aressem @hmusum FYI

2022-09-30 12:09 UTC, baldersheim approved these changes
Let us run with basic system test to ensure basics works

2022-09-30 13:54 UTC, baldersheim commented
Not quite right yet.
 14:51:55 [2022-09-30 12:36:43.342] WARNING searchnode       stderr	/bin/sh: /opt/vespa/sbin/vespa-proton: No such file or directory
14:51:55 [2022-09-30 12:36:43.342] WARNING distributor      stderr	/bin/sh: /opt/vespa/sbin/vespa-distributord: No such file or directory

2022-09-30 13:55 UTC, baldersheim requested changes
See runtime errors

2022-10-03 09:52 UTC, toregge commented on storageserver/src/apps/storaged/CMakeLists.txt
> +install_absolute_symlink(vespa-storaged-bin sbin/vespa-distributord-bin)
The first argument to` install_absolute_symlink` needs to start with `sbin/`

2022-10-04 12:30 UTC, baldersheim approved these changes

2022-10-04 12:30 UTC, merged