Jonmv/configurable zk session timeout
vespa-engine/vespa pull request #24451
Opened 2022-10-14 12:19 UTC by jonmv

@hakonhall please review, but don't merge.

2022-10-14 12:23 UTC, hakonhall approved these changes

2022-10-21 08:55 UTC, hakonhall approved these changes

2022-11-09 15:27 UTC, jonmv commented
@bratseth perhaps something like this, to allow users to set that session timeout themselves?

2022-11-10 08:14 UTC, bratseth requested changes
LGTM (but don't make getConfig a noop for configservers).

2022-11-10 08:14 UTC, bratseth commented on config-model/src/main/java/com/yahoo/vespa/model/container/ApplicationContainerCluster.java
> +        if (getParent() instanceof ConfigserverCluster) return; // Produces its own config
```suggestion
```

2022-11-10 09:59 UTC, hakonhall approved these changes

2022-11-11 14:14 UTC, merged