collect(Collectors.toList()) -> toList()
vespa-engine/vespa pull request #25097
Opened 2022-12-02 22:38 UTC by baldersheim

@hmusum or @bjorncs PR

2022-12-02 23:00 UTC, hmusum approved these changes

2022-12-02 23:01 UTC, hmusum requested changes
Some UnsupportedOperationException need to be fixed

2022-12-03 16:36 UTC, baldersheim commented
Let us see if there are more assumptions on the modifiability of Collectors.toList()...

2022-12-03 16:36 UTC, merged

2022-12-03 20:43 UTC, hmusum commented
👍