Avoid flushing components in proton more than necessary.
vespa-engine/vespa pull request #25282
Opened 2022-12-16 16:47 UTC by geirst

Don't consider TLSSIZE ordering if there exists an active (ongoing) flush (for the same flush handler) that started before the last flush time of the flush target to evaluate. Instead we should wait for the active (ongoing) flush to be finished before doing another evaluation.

@baldersheim please review
@toregge FYI

2022-12-16 17:17 UTC, baldersheim requested changes
I would prefer using steady_time over system_time. We should try to avoid that.

2022-12-16 17:17 UTC, baldersheim commented on searchcore/src/vespa/searchcore/proton/flushengine/flushengine.h
>          vespalib::system_time getStart() const { return vespalib::system_clock::now() - std::chrono::duration_cast<vespalib::system_time::duration>(elapsed()); }
rename getStart -> getStartInEpoch and make repurpose getStart to return steady_time.

2022-12-16 17:17 UTC, baldersheim commented on searchcore/src/vespa/searchcore/proton/flushengine/active_flush_stats.h
> +    using StatsMap = vespalib::hash_map<vespalib::string, vespalib::system_time>;
use vespalib::steady_time instead. That is a lot safer than using system_time.

2022-12-19 10:04 UTC, geirst commented
Discussed with @baldersheim offline. We decided to change to using vespalib::steady_time in a follow-up PR as it involves changing all implementations of IFlushTarget (getLastFlushTime).

2022-12-19 10:04 UTC, baldersheim approved these changes
Using steady_time should be done in separate PR as it requires some more changes.

2022-12-19 10:04 UTC, merged

2022-12-19 13:38 UTC, geirst commented
After further investigation we found that changing to steady_time is not feasible as the implementations of IFlushTarget::getLastFlushTime() use time stamps on disk files (system_time).