Fix dimension hashing bug
vespa-engine/vespa pull request #25280
Opened 2022-12-16 15:21 UTC by gjoranv

FYI: @hakonhall

2022-12-16 16:00 UTC, hakonhall approved these changes

2022-12-16 16:33 UTC, baldersheim requested changes
Either a set as suggested by @hakonhall or 
hash += Hasher.xx3(dim.id.getBytes(UTF8)) + Hasher.xx3(dim.value.getBytes(UTF8))

2022-12-16 16:33 UTC, baldersheim commented on metrics-proxy/src/main/java/ai/vespa/metricsproxy/service/MetricsParser.java
> +            valueHash += dim.value.hashCode();
Very good catch @gjoranv. This was way to naive.
We can not treat key and value separately.
I suggest using com.yahoo.compress.Hasher.xxh3 and just keep one 64bit.
Either that or follow @hakonhall's suggestion.

2022-12-16 16:33 UTC, baldersheim commented on metrics-proxy/src/test/java/ai/vespa/metricsproxy/service/MetricsParserTest.java
> +        System.out.println(dimensionsHashCode(dimensions2));
I added test and also removed the 2 System.out.println lines assuming they were debug.

2022-12-16 16:42 UTC, baldersheim reviewed
Looking at the code and the history the key point was to detect unique Dimension sets.
And using a set seems a lot safer.

2022-12-18 15:03 UTC, baldersheim approved these changes

2022-12-18 15:03 UTC, merged

2022-12-19 08:01 UTC, gjoranv commented
👍

2022-12-19 09:33 UTC, baldersheim commented on metrics-proxy/src/main/java/ai/vespa/metricsproxy/service/MetricsParser.java
> +    static long dimensionsHashCode(List<Dimension> dimensions) {
Yes, it could

2022-12-19 09:35 UTC, baldersheim commented
A benchmark after that change show parse time increased around 15-20% when using set. No effect on the memory footprint which is the most important measure here.