Preserve original exception when deployments fail to read from S3
vespa-engine/vespa pull request #26247
Opened 2023-03-01 11:16 UTC by jonmv

@hmusum or @freva please review and merge

2023-03-01 11:46 UTC, hmusum approved these changes

2023-03-01 12:40 UTC, hmusum requested changes
Build fails with:

[ERROR] /sd/workspace/src/github.com/vespa-engine/vespa/controller-server/src/main/java/com/yahoo/vespa/hosted/controller/ApplicationController.java:[638,18] cannot infer type for local variable postDeployment

2023-03-01 13:24 UTC, jonmv commented
😢

2023-03-01 20:30 UTC, hmusum approved these changes

2023-03-01 21:05 UTC, merged

2023-03-02 10:02 UTC, jonmv commented
Wonder if it was JDK18 locally that made this pass?