Avoid presizing memory up front fro the BufferStates vector.
vespa-engine/vespa pull request #26404
Opened 2023-03-11 15:12 UTC by baldersheim

@toregge and @geirst PR
Prior to this PR _states array was only accessed by write thread.
This PR uses a deque instead of a presized vector.
Currently not possible to grow with a vector due to BufferState exposes references to its internal member levaving it non-movable.

2023-03-11 19:33 UTC, toregge requested changes
```
00:24:37 The following tests FAILED:
00:24:37 	368 - searchlib_attribute_test_app (Failed)
00:24:37 	382 - searchlib_enumstore_test_app (Failed)
00:24:37 	689 - vespalib_array_store_test_app (Failed)
00:24:37 	694 - vespalib_datastore_test_app (Failed)
00:24:37 Errors while running CTest 
```

2023-03-12 09:37 UTC, toregge commented on vespalib/src/vespa/vespalib/datastore/datastorebase.cpp
> +    extra_allocated += _states.size() * sizeof(BufferState);
Getting size of _states can race with adding new element to _states.

2023-03-12 09:49 UTC, toregge commented
`DataStoreBase::getAddressSpaceUsage()` is broken, limitArrays value becomes
too low when not accounting for future resize of `_states`.

2023-03-12 09:52 UTC, toregge commented
Iterating over `_states` races with growing `_states`.

2023-03-12 09:55 UTC, toregge commented on vespalib/src/vespa/vespalib/datastore/datastorebase.cpp
> +        _states.emplace_back();
A new state element dosn't know if free lists or elem hold lists are enabled.

2023-03-13 12:53 UTC, baldersheim commented
See #26417 instead.

2023-03-13 12:53 UTC, closed without merging