Jonmv/two phase deploy
vespa-engine/vespa pull request #29968
Opened 2024-01-18 14:30 UTC by jonmv

@hmusum please review, but don't merge yet.

2024-01-18 14:53 UTC, hmusum commented on configserver/src/main/java/com/yahoo/vespa/config/server/http/v2/response/SessionPrepareAndActivateResponse.java
> -                              "/instance/" + applicationId.instance().value());
I don't think you can change field names and remove something here, this is a documented API:
https://docs.vespa.ai/en/reference/deploy-rest-api-v2.html#prepareandactivate

2024-01-18 14:54 UTC, hmusum requested changes
Looks good, except changing/removing some stuff in response

2024-01-19 07:23 UTC, jonmv commented
Ah, I didn't think this one was public. I'll re-add those fields, then.

2024-01-19 08:19 UTC, hmusum approved these changes

2024-01-19 08:43 UTC, merged