allow inputs { query(foo) string }
vespa-engine/vespa pull request #30359
Opened 2024-02-21 14:53 UTC by arnej27959

@bratseth please review
not really sure how useful this is, the effect is the same as if the input was not declared at all.

2024-02-21 15:03 UTC, bratseth requested changes, later dismissed
... otherwise LGTM!

2024-02-21 15:03 UTC, bratseth commented on container-search/src/main/java/com/yahoo/search/query/properties/RankProfileInputProperties.java
> +                    e.printStackTrace();
Remove printlns, and throw ...

2024-02-21 20:01 UTC, arnej27959 commented on container-search/src/main/java/com/yahoo/search/query/properties/RankProfileInputProperties.java
> +                    e.printStackTrace();
ouch, will fix.

2024-02-22 11:35 UTC, arnej27959 commented
@bratseth please take another look now
@hmusum FYI - handles SD with "long" now

2024-02-22 12:28 UTC, bratseth approved these changes
👍

2024-02-22 12:29 UTC, bratseth commented
Was there something with demanding newline breaking something that needs to be handled before merging?

2024-02-22 13:52 UTC, hmusum commented
I think we can merge this, the integration test failed with:

`Failed parsing rank-profile from 'related_articles_factual_grade.profile': Encountered " <IDENTIFIER> "long"" at line 4, column 41.

Was expecting one of:

"\n" ...
    <TENSOR_TYPE> ...
    "}" ...
    ":" ...
    "double" ...
    
At position:
       query(storyRecentSpikeStartTime) long: 0`

and handling long seems to be covered by this PR. 
If there are still issues the integration test should cover that as well.

2024-02-22 14:08 UTC, merged