Move Results to the only place it is used.
vespa-engine/vespa pull request #30959
Opened 2024-04-18 11:15 UTC by baldersheim

@bjorncs PR

2024-04-19 05:11 UTC, bjorncs requested changes
PR build fails with:
```
 [ERROR] com.yahoo.application.ApplicationTest.application_with_query_profile_sets_up_query_profile_registry -- Time elapsed: 0.063 s <<< ERROR!
23:22:16 java.lang.RuntimeException: When resolving dependencies of 'federation in native' of type 'com.yahoo.search.federation.FederationSearcher'
23:22:16 Caused by: java.lang.RuntimeException: Can't create ComponentRegistry of unknown type com.yahoo.search.federation.selection.TargetSelector<?>
23:22:16 	at com.yahoo.container.di.componentgraph.core.ComponentGraph.getComponentRegistry(ComponentGraph.java:229)
23:22:16 	at com.yahoo.container.di.componentgraph.core.ComponentGraph.handleParameter(ComponentGraph.java:201)
23:22:16 	at com.yahoo.container.di.componentgraph.core.ComponentGraph.lambda$completeNode$8(ComponentGraph.java:182)
```

2024-04-19 19:03 UTC, baldersheim commented
Fixed, and also avoided use of exceptions in normal control flow. @bjorncs or @bratseth PTAL

2024-04-19 20:03 UTC, bratseth approved these changes

2024-04-19 20:04 UTC, bratseth approved these changes

2024-04-19 20:05 UTC, merged

2024-04-22 06:01 UTC, bjorncs reviewed
See comment