Cache-friendly prime table
vespa-engine/vespa pull request #31993
Opened 2024-07-21 09:22 UTC by blacktea

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

This PR optimizes the getting modulo method. Based on the benchmarks https://quick-bench.com/q/FrBEHCD4SpgHG_yTchhkWgrY0SI, the performance increased by 23 times.

Method:
The original `__stl_prime_list` table is split into arrays of 8 elements. It allows the cache line to accommodate these arrays decreasing cache misses.
The `__upper_bound_list_size` array is used to find a nested array where the given `newSize` is located.

Testing:
The method is checked here: https://godbolt.org/z/bd7rM71f6

2024-07-22 10:22 UTC, blacktea commented
Note: I'd avoid using double underscores as well since they are supposed to be reserved by compilers. 
Let me know if you want me to rename variable names.

2024-08-12 11:42 UTC, baldersheim requested changes

2024-08-14 09:31 UTC, jonmv commented
If this is a critical piece of code, it's much faster to find the relevant part of the list straight from the order of the msb: https://quick-bench.com/q/9W-F5Q5sCBJr96PXjsPq2a9PFGU, and then comparing the only two relevant elements. I have no idea how to write C++, though, so don't look too hard at the details :p Also, this is obviously only true while the list has the property that the primes are between consecutive powers of two (except for the first one, which is handled with the `+ 8` 🙈).

2024-08-14 10:03 UTC, baldersheim commented
I have never observed this as consuming time. Perhaps @blacktea can add some info on how this was observed ?
I agree the optimal solution would be to use the msb as lookup index.

2024-08-19 08:42 UTC, baldersheim commented
@blacktea Do you intend to complete this one anytime soon ?

2024-08-19 10:46 UTC, baldersheim commented
Implemented msb index lookup in #32168, closing

2024-08-19 10:46 UTC, closed without merging