Fixed hardcoded doc ids in significance model generator
vespa-engine/vespa pull request #32521
Opened 2024-10-04 11:14 UTC by glebashnik

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2024-10-04 12:52 UTC, geirst requested changes
Overall looks good, please add unit test.

2024-10-04 12:52 UTC, geirst commented on document/src/main/java/com/yahoo/document/json/JsonReader.java
> +    public ParsedDocumentOperation readSingleDocument() {
Please add unit test for the new function in document/src/test/java/com/yahoo/document/json/JsonReaderTestCase.java.

2024-10-07 12:23 UTC, glebashnik commented
@geirst New implementation, avoids changes in JsonReader.
Uses dummy doc type and doc id instead.
They don't matter as long as doc type is in doc id.
We are only interested in content.
Made unit tests for model generator more robust.

2024-10-07 13:32 UTC, geirst approved these changes

2024-10-09 10:58 UTC, merged