Validate athenz-domain in deployment.xml equal to tenant domain
vespa-engine/vespa pull request #4267
Opened 2017-11-24 07:24 UTC by tokle

2017-11-24 07:48 UTC, mpolden approved these changes
LGTM

2017-11-24 12:47 UTC, bjorncs reviewed
See comments

2017-11-24 12:47 UTC, bjorncs commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/restapi/application/DeployAuthorizer.java
> +    public DeployAuthorizer(ZoneRegistry zoneRegistry, AthenzClientFactory athenzClientFactory, ApplicationPackage applicationPackage) {
Why is `ApplicationPackage` a constructor argument. I would make it an argument to `throwIfUnauthorizedForDeploy` instead.

2017-11-24 12:47 UTC, bjorncs commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/restapi/application/DeployAuthorizer.java
> +
Note the above return statement (line 47)!

2017-11-24 12:47 UTC, bjorncs requested changes
See comments

2017-11-27 08:30 UTC, tokle commented
@bjorncs ptal

2017-11-27 10:43 UTC, bjorncs approved these changes

2017-11-27 10:43 UTC, merged