Refactor identityprovider. Add SiaIdentityProvider
vespa-engine/vespa pull request #4984
Opened 2018-02-08 21:20 UTC by tokle

2018-02-09 10:25 UTC, bjorncs approved these changes
We'll have to rewrite our integration test before merging this.

2018-02-09 10:25 UTC, bjorncs commented on container-disc/src/main/java/com/yahoo/container/jdisc/athenz/impl/AthenzIdentityProviderImpl.java
>              SSLContext sslContext = SSLContext.getInstance("TLSv1.2");
Consider replacing this code with `AthenzSslContextBuilder` from _vespa-athenz_

2018-02-09 10:25 UTC, bjorncs commented on container-disc/src/main/java/com/yahoo/container/jdisc/athenz/AthenzIdentityProvider.java
>  public interface AthenzIdentityProvider {
Consider moving this to `vespa-athenz`.

2018-02-09 10:28 UTC, bjorncs commented
`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:testCompile (default-testCompile) on project container-disc: Compilation failure: Compilation failure:
[ERROR] /source/container-disc/src/test/java/com/yahoo/container/jdisc/athenz/impl/AthenzIdentityProviderImplTest.java:[87,47] cannot find symbol
[ERROR] symbol:   method getNToken()
[ERROR] location: variable identityProvider of type com.yahoo.container.jdisc.athenz.AthenzIdentityProvider
[ERROR] /source/container-disc/src/test/java/com/yahoo/container/jdisc/athenz/impl/AthenzIdentityProviderImplTest.java:[119,47] cannot find symbol
[ERROR] symbol:   method getNToken()
[ERROR] location: variable identityProvider of type com.yahoo.container.jdisc.athenz.AthenzIdentityProvider
[ERROR] /source/container-disc/src/test/java/com/yahoo/container/jdisc/athenz/impl/AthenzIdentityProviderImplTest.java:[158,47] cannot find symbol
[ERROR] symbol:   method getNToken()
[ERROR] location: variable identityProvider of type com.yahoo.container.jdisc.athenz.AthenzIdentityProvider
[ERROR] -> [Help 1]
[ERROR] `

2018-02-13 14:32 UTC, tokle commented on vespa-athenz/src/main/java/com/yahoo/vespa/athenz/identity/package-info.java
> +@ExportPackage
add copyright

2018-02-16 14:25 UTC, bjorncs requested changes

2018-02-16 14:25 UTC, bjorncs commented on athenz-identity-provider-service/src/main/java/com/yahoo/vespa/hosted/athenz/identityprovider/AthenzIdentityProviderImpl.java.orig
> +// Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
`AthenzIdentityProviderImpl.java.orig` - Emacs accident?

2018-02-16 14:25 UTC, bjorncs commented on vespa-athenz/src/main/java/com/yahoo/vespa/athenz/identity/package-info.java
> +@ExportPackage
Copyright still missing :)

2018-02-16 14:25 UTC, bjorncs commented on vespa-athenz/src/main/java/com/yahoo/vespa/athenz/identity/SiaIdentityProvider.java
> +package com.yahoo.vespa.athenz.identity;
Add copyright

2018-02-16 14:25 UTC, bjorncs commented on vespa-athenz/src/main/java/com/yahoo/vespa/athenz/identity/SiaIdentityProvider.java
> +public class SiaIdentityProvider implements AthenzIdentityProvider {
Add author :)

2018-02-16 14:25 UTC, bjorncs commented on container-disc/src/main/java/com/yahoo/container/jdisc/Ckms.java
> +public interface Ckms {
Consider adding author

2018-02-16 16:18 UTC, tokle commented on athenz-identity-provider-service/src/main/java/com/yahoo/vespa/hosted/athenz/identityprovider/AthenzIdentityProviderImpl.java.orig
> +// Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
git reset accident ...

2018-02-16 16:22 UTC, tokle commented
@bjorncs ptal

2018-02-16 21:26 UTC, bjorncs approved these changes

2018-02-20 06:24 UTC, merged