Remove junit.fdramework usage
vespa-engine/vespa pull request #5199
Opened 2018-03-02 14:35 UTC by bratseth

Nothing to see here ...

2018-03-02 15:08 UTC, gjoranv requested changes
Please check your IDEA settings:
Editor -> Code style -> Java -> Imports (tab)

I suggest to set an insanely high number for 'Class count' and 'Names count'

Tip (you probably already know) to optimize imports: Ctrl+Alt+O

2018-03-02 15:08 UTC, gjoranv commented on clustercontroller-utils/src/test/java/com/yahoo/vespa/clustercontroller/utils/communication/http/AsyncHttpClientWithBaseTest.java
> +import static org.junit.Assert.*;
Wildcard imports are evil..

2018-03-02 15:08 UTC, gjoranv commented on config-model/src/test/java/com/yahoo/vespa/model/builder/xml/dom/chains/search/DomFederationSearcherBuilderTest.java
> +import static org.junit.Assert.*;
Wildcard import..

2018-03-02 15:08 UTC, gjoranv commented on config-model/src/test/java/com/yahoo/vespa/model/builder/xml/dom/chains/search/DomSearchChainsBuilderTest.java
> +import static org.junit.Assert.*;
Wildcard import. Please check your settings in IntelliJ

2018-03-02 15:08 UTC, gjoranv commented on config-model/src/test/java/com/yahoo/vespa/model/content/IndexedHierarchicDistributionTest.java
> +import static org.junit.Assert.*;
Wildcard

2018-03-02 15:08 UTC, gjoranv commented on config-model/src/test/java/com/yahoo/vespa/model/test/PortsMetaTestCase.java
> +import static org.junit.Assert.*;
Wildcard

2018-03-02 15:08 UTC, gjoranv commented on config/src/test/java/com/yahoo/config/subscription/ConfigSubscriptionTest.java
> +import static org.junit.Assert.*;
Wildcard

2018-03-02 15:08 UTC, gjoranv commented on config/src/test/java/com/yahoo/vespa/config/ConfigDefinitionKeyTest.java
> +import static org.junit.Assert.*;
Wildcard

2018-03-02 15:08 UTC, gjoranv commented on config/src/test/java/com/yahoo/vespa/config/ConfigDefinitionSetTest.java
> +import static org.junit.Assert.*;
Wildcard

2018-03-02 15:08 UTC, gjoranv commented on config/src/test/java/com/yahoo/vespa/config/RawConfigTest.java
> +import static org.junit.Assert.*;
Wildcard

2018-03-02 15:08 UTC, gjoranv commented on container-search/src/test/java/com/yahoo/fs4/test/PacketDecoderTestCase.java
> +import static org.junit.Assert.*;
Wildcard (It was originally as well, but please fix when touching it)

2018-03-02 15:08 UTC, gjoranv commented on container-search/src/test/java/com/yahoo/fs4/test/PacketTestCase.java
> +import static org.junit.Assert.*;
Wildcard

2018-03-02 15:08 UTC, gjoranv commented on container-search/src/test/java/com/yahoo/prelude/cache/test/CacheTestCase.java
> +import static org.junit.Assert.*;
Wildcard

2018-03-05 08:28 UTC, bratseth commented
New Mac problems. Fixed & merging.

2018-03-05 08:28 UTC, merged

2018-03-05 10:45 UTC, gjoranv commented
👍