Balder/do not pregenerate reason
vespa-engine/vespa pull request #5416
Opened 2018-03-22 20:49 UTC by baldersheim

@vekterli PR

2018-03-23 14:16 UTC, vekterli requested changes
Overall looks good, but I would really like to see more message meta data emitted in the message tracker status page before pulling this in. Should not add any  overhead, since all the relevant metadata is present without any heap allocs etc already.

2018-04-03 16:59 UTC, baldersheim commented on messagebus/src/vespa/messagebus/routing/routingtable.cpp
> +        _routes.insert(std::map<string, Route>::value_type(routeSpec.getName(), std::move(route)));
Fixed

2018-04-03 16:59 UTC, baldersheim commented on messagebus/src/vespa/messagebus/routing/routingtable.cpp
> +        _hops.insert(std::map<string, HopBlueprint>::value_type(hopSpec.getName(), HopBlueprint(hopSpec)));
Fixed

2018-04-03 17:17 UTC, baldersheim commented on storage/src/vespa/storage/distributor/activecopy.cpp
> +        if (idealState[i] == node) _ideal = i;
Done

2018-04-03 17:17 UTC, baldersheim commented on storage/src/vespa/storage/distributor/activecopy.h
> +    uint16_t nodeIndex;
Done

2018-04-03 17:18 UTC, baldersheim commented on storage/src/vespa/storage/distributor/activecopy.h
> +public:
Done

2018-04-03 22:37 UTC, baldersheim commented
Closing as it is superceeded by #5451

2018-04-03 22:37 UTC, closed without merging