Only produce qrsearchers config with local dispatcher present.
vespa-engine/vespa pull request #5472
Opened 2018-04-05 17:03 UTC by baldersheim

@hmusum, @bratseth or @jobergum or any other inclined to get dirty

2018-04-05 17:05 UTC, baldersheim commented on config-model/src/main/java/com/yahoo/vespa/model/container/search/ContainerSearch.java
> +                                host(tld.getHostname()).
Now the hostname could be replaced with "localhost". Not sure if that is desirable or not.

2018-04-06 05:35 UTC, hmusum commented on config-model/src/main/java/com/yahoo/vespa/model/container/ContainerCluster.java
> +Qr     * prefix should never considered available for direct use by customers, and
Remove unintentionally added characters

2018-04-06 05:36 UTC, hmusum requested changes
Except the invalid syntax due to stray characters, LGTM

2018-04-06 07:59 UTC, baldersheim commented
Given that this is the output from configproxy
{code}
[0] honda:~/git/systemtests/tests/search/reportcoverage$ vespa-configproxy-cmd |grep ClusterSea | grep qr-searchers
container.qr-searchers,combinedcontainer/searchchains/chain/search/component/com.yahoo.prelude.cluster.ClusterSearcher,3,22f0ecd3defd7c9b0c37760b2311d412
container.qr-searchers,doc-api/searchchain/chain/search/component/com.yahoo.prelude.cluster.ClusterSearcher,3,22f0ecd3defd7c9b0c37760b2311d412
{code}

I guess this approach is not possible. There is nothing in the config id that will enable it to reach the instance. In that case this will never work as it has no idea about hostname.
@gjoranv Or is there any magic I am not aware of.
I will build and run a system test first.

2018-04-06 08:28 UTC, bratseth approved these changes

2018-04-06 11:26 UTC, baldersheim commented
Closing as it seems this was a dead end

2018-04-06 11:26 UTC, closed without merging

2018-04-09 09:42 UTC, gjoranv commented
@baldersheim The components are children of the ContainerCluster, not the Container. Why did you have to move the config generation to Container?

2018-04-09 10:16 UTC, baldersheim commented
Because I wanted to limit the set of dispatch nodes to only contain the ones on the same host. So the hostname was needed. But since that was not possible, I did it in the ClusterSearcher instead.