Container-jersey2: Scala code replaced with Java
vespa-engine/vespa pull request #6020
Opened 2018-05-31 09:42 UTC by ollivir

2018-06-01 11:40 UTC, bjorncs requested changes

2018-06-01 11:40 UTC, bjorncs commented on container-jersey2/src/main/java/com/yahoo/container/servlet/jersey/JerseyServletProvider.java
> +            // ignored
Should this exception be ignored?

2018-06-01 11:40 UTC, bjorncs commented on container-jersey2/src/main/java/com/yahoo/container/servlet/jersey/ResourceOrProviderClassVisitor.java
> +        super(Opcodes.ASM5);
Use ASM6 as in @gjoranv's recent PR: https://github.com/vespa-engine/vespa/pull/5919/files#diff-8.

2018-06-01 11:42 UTC, bjorncs commented on container-jersey2/src/main/java/com/yahoo/container/servlet/jersey/ResourceOrProviderClassVisitor.java
> +        super(Opcodes.ASM5);
EDIT: Noticed that the PR was not merged. Ignore above comment.

2018-06-01 11:42 UTC, bjorncs approved these changes

2018-06-01 12:35 UTC, ollivir commented on container-jersey2/src/main/java/com/yahoo/container/servlet/jersey/JerseyServletProvider.java
> -        return Optional.empty();
The previous version here as questioned by @bjorncs was slightly different in behaviour than the Scala version. This change should bring it closer.

2018-06-01 12:35 UTC, ollivir commented on container-jersey2/src/main/java/com/yahoo/container/servlet/jersey/ComponentGraphProvider.java
> + * Resolves jdisc container components for jersey 2 components.
Jersey 1 comment wiped.

2018-06-04 14:28 UTC, bjorncs approved these changes

2018-06-04 14:28 UTC, merged