Precompute and store attribute and executor id together in a single h…
vespa-engine/vespa pull request #6219
Opened 2018-06-16 07:38 UTC by baldersheim

…ashmap.

the executor id so complex fields use the same executor.
@toregge and @geirst PR

2018-06-16 14:19 UTC, toregge requested changes
Please ensure consistent mapping to executor id.

2018-06-16 14:19 UTC, toregge commented on searchcore/src/vespa/searchcore/proton/attribute/attribute_writer.cpp
> +        _attrMap[attr->getName()] = AttrWithId(attr, _attributeFieldWriter.getExecutorId(prefix));
This doesn't match how executor id is set in FieldContext constructor.

2018-06-16 19:12 UTC, baldersheim commented
Unified selection of executorId.

2018-06-16 20:33 UTC, toregge commented
Doesn't match executor id used in AttributeWriter::heartBeat(), AttributeWriter::onReplayDone(),
AttributeWriter::compactLidSpace(), FlushableAttribute::initFlush(), ExclusiveAttributeReadAccessor::takeGuard(), AttributeManager::asyncForEachAttribute(), 
FilterAttributeManager::asyncForEachAttribute(), GidToLidChangeListener::GidToLidChangeListener(),
and allocShrinker() (not necessarily a complete list).

2018-06-17 20:46 UTC, baldersheim commented
Now, I think I have caught all of them ..

2018-06-18 09:40 UTC, toregge approved these changes
LGTM

2018-06-18 09:58 UTC, merged

2018-06-18 11:46 UTC, geirst reviewed
@baldersheim FYI

2018-06-18 11:46 UTC, geirst commented on searchcore/src/vespa/searchcore/proton/attribute/attribute_writer.h
> +    void setupAttriuteMapping();
Typo: Attriute -> Attribute