use com.optimaize.langdetect for lang detection
vespa-engine/vespa pull request #6452
Opened 2018-07-24 06:48 UTC by jefimm

https://github.com/vespa-engine/vespa/issues/6403

2018-07-24 10:20 UTC, bratseth approved these changes

2018-07-24 11:57 UTC, gjoranv commented
Please hold merge until I've added a commit to fix the dependencies. The purpose of the enforcer is to prevent adding any dependencies that are not provided at runtime to the maven tree of external plugin developers.

2018-07-24 15:56 UTC, gjoranv requested changes

2018-07-24 15:56 UTC, gjoranv commented on container-dependencies-enforcer/pom.xml
> +                                                <include>com.optimaize.languagedetector:language-detector:0.6:jar:provided</include>
Please remove all changes in dependencies-enforcer pom.
See #6460

2018-07-24 16:55 UTC, jefimm commented
@gjoranv  done

2018-07-24 19:18 UTC, gjoranv commented
The container-dev module is only a helper pom for plugin development. When developing a searcher plugin, users should add a dependency to the `container` maven artifact, which includes container-dev. The exclusions are done to "hide" the apis that are _not_ exported runtime from the osgi container, to force users to add them explicitly in their own pom. Otherwise, you could have a working build, but a runtime failure because the classes are not available.

The libraries referred to here will be available for the linguistics module inside the container, but not for code outside the bundle that contains the linguistics code.

2018-07-24 19:21 UTC, jefimm commented
@gjoranv  Could you please advise how to fix the failing tests ?

2018-07-24 21:14 UTC, gjoranv commented
I think I see what the problem is. Our internal pom files generate the wrong test classpath. I will try to get it fixed tonight or tomorrow morning outside this PR.

2018-07-25 11:35 UTC, gjoranv approved these changes

2018-07-25 11:36 UTC, merged