henrhoi/post-api-requestmap-change
vespa-engine/vespa pull request #6520
Opened 2018-08-08 14:45 UTC by henrhoi

Now adding all entries from request.propertyMap() to requestMap, which will be overwritten if duplicate in JSON payload

2018-08-08 15:06 UTC, bratseth requested changes

2018-08-08 15:13 UTC, henrhoi commented on container-search/src/main/java/com/yahoo/search/handler/SearchHandler.java
> +            request.propertyMap().forEach(requestMap::put);
Ah, I though it was the other way around... My bad, I will correct it.

2018-08-09 11:42 UTC, henrhoi commented
@bratseth Added requested changes

2018-08-09 11:45 UTC, bratseth approved these changes

2018-08-09 11:45 UTC, merged