Add query override of rerank-count
vespa-engine/vespa pull request #6811
Opened 2018-09-05 13:01 UTC by lesters

2018-09-05 14:10 UTC, havardpe commented on searchcore/src/vespa/searchcore/proton/matching/match_tools.cpp
> +    uint32_t heapSize = hitcollector::HeapSize::lookup(_queryEnv.getProperties(), _rankSetup.getHeapSize());
the override should be injected into the rank setup to avoid double override detection

2018-09-05 14:12 UTC, baldersheim commented on searchcore/src/vespa/searchcore/proton/matching/match_tools.cpp
> +    uint32_t heapSize = hitcollector::HeapSize::lookup(_queryEnv.getProperties(), _rankSetup.getHeapSize());
Do not look it up again here. Just take heapSize in as an argument to createDiversity(uint32 heapSize);
It has already been resolved at the callsite and is present as params.heapSize in MatchMaster::match

2018-09-05 14:16 UTC, baldersheim requested changes

2018-09-05 14:16 UTC, baldersheim commented on searchcore/src/vespa/searchcore/proton/matching/matcher.cpp
>  using namespace search::fef::indexproperties::matching;
Only import what you need using namespace search::fef::indexproperties::hitcollector.

2018-09-06 07:56 UTC, baldersheim commented on searchcore/src/vespa/searchcore/proton/matching/matcher.cpp
> +                                                                                          _rankSetup->getHeapSize());
There is an extra space.
Also it is better to add a using HeapSize = search::fef::indexproperties::hitcollector::HeapSize.
Having to break long lines due to very long names just makes a mess.

2018-09-06 09:03 UTC, baldersheim approved these changes

2018-09-07 08:28 UTC, merged