Lesters/add model eval rest api
vespa-engine/vespa pull request #6981
Opened 2018-09-17 14:18 UTC by lesters

@bratseth Please review.

2018-09-18 10:17 UTC, bratseth approved these changes
LGTM!

2018-09-18 10:17 UTC, bratseth commented on model-evaluation/src/main/java/ai/vespa/models/handler/ModelsEvaluationHandler.java
> +            if (bindingName.startsWith("constant(")) {
Ok, but I think we need another way to do this which only exposes the external bindings.

2018-09-18 17:11 UTC, bratseth commented
Also, I think most of the return status codes should be 404 not 400.

2018-09-18 17:13 UTC, bratseth commented
You also need to add a package-info with @ExportPackage (but not @PublicApi) in the handler package.

2018-09-18 17:15 UTC, bratseth requested changes
be sure to add the package-info file before merging

2018-09-18 23:29 UTC, bratseth approved these changes

2018-09-18 23:29 UTC, bratseth commented
I did my suggestions, merging.

2018-09-18 23:29 UTC, merged

2018-09-19 08:36 UTC, lesters commented
Thanks! I'll refactor with the TODOs you've added in mind.

Regarding ExportPackage, I'm pretty sure this is not required for this handler as it is not supposed to be used programatically. I tested building, running and querying the API successfully before committing.

2018-09-19 12:58 UTC, bratseth commented
How can dependency injection create it if it cannot access it?

2018-09-19 13:52 UTC, lesters commented
Well, doesn't this also go for user created application packages? We don't require them the ExportPackage either?

2018-09-19 16:30 UTC, bratseth commented
Good point; However, I think it is needed still because the handler is referenced in the config model.

2018-09-20 08:37 UTC, lesters commented
That is true. Most probably this worked due to the fat jar in config model so it was contained there anyway. I will decouple this.