Balder/add in memory crc for summary cache
vespa-engine/vespa pull request #7045
Opened 2018-09-21 11:22 UTC by baldersheim

@geirst and @toregge PR
Best reviewed in sequence. Only the last adds any semantics

2018-09-21 11:58 UTC, toregge approved these changes
LGTM

2018-09-21 12:00 UTC, toregge commented
Please update unit tests, so they pass too.

2018-09-21 12:27 UTC, geirst approved these changes
Overall looks good, some nitpicks to look at.

2018-09-21 12:27 UTC, geirst commented on searchlib/src/vespa/searchlib/docstore/value.cpp
> +// Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
Please update year

2018-09-21 12:27 UTC, geirst commented on searchlib/src/vespa/searchlib/docstore/value.h
> +// Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
Please update year

2018-09-21 12:27 UTC, geirst commented on searchlib/src/vespa/searchlib/docstore/value.h
> +class Value {
Consider adding class comment

2018-09-21 12:27 UTC, geirst commented on searchlib/src/vespa/searchlib/docstore/documentstore.cpp
> +            LOG(warning, "Summary cache for lid %u is corrupt. Invalidating and reading directly backing store", lid);
Missing word? "directly backing store" -> "directly from backing store"?

2018-09-21 12:28 UTC, geirst requested changes
Unit test must be fixed: "384 - searchlib_logdatastore_test_app (Failed)"

2018-09-24 09:52 UTC, baldersheim commented
@geirst PR Now it should be OK.

2018-09-24 10:21 UTC, merged

2018-09-24 10:25 UTC, geirst reviewed
👍