Bring the .search.ClusterSearcher to a known state during construction.
vespa-engine/vespa pull request #7348
Opened 2018-10-17 21:58 UTC by baldersheim

Also wait until SearchCluster knows the cluster state.
And the .prelude.ClusterSearcher should also wait for known state in constructor.
Update tests
@bratseth and @arnej27959 PR
I am a bit uncertain about the state for the PingTest of the .search.ClusterSearcher. The grumpy server and the passive aggresive, can not work as the test is today.

2018-10-18 07:37 UTC, bratseth requested changes
For the internal search clusters (prelude.SearchCluster) - it is the cluster searcher constructor that does the waiting. If that works in this case (depending on the construction dependencies - I didn't check), that is good as it makes the code simpler (we can remove the separate component to carry over cluster state as the new SearchCluster instance won't mess with it prematurely). I don't think we had an issue here though.

For the external clusters (federation - search.clusterSearcher) case, you do not wait in the SearchCluster constructor but rely on the downstream providers to do the waiting - and in the dispatch case even driving the pings themselves. This will not work because most such provider searchers belong to the applications, not us. For this code path i did look at it when we discussed this and to me it looked like it would work here to do it in the SearchCluster constructor. Any particular reason you didn't?

2018-10-18 07:37 UTC, bratseth commented on container-search/src/main/java/com/yahoo/search/cluster/TrafficNodeMonitor.java
> +            for (long remain = doom - System.currentTimeMillis(); atStartUp && remain > 0; remain = doom - System.currentTimeMillis()) {
Strange use of a for loop, but ok.

2018-10-18 07:37 UTC, bratseth commented on container-search/src/main/java/com/yahoo/prelude/cluster/ClusterSearcher.java
> +    private void waitUntilStateIsDetermined() {
Could you use either "known" or "determined" in both code paths?

2019-08-22 06:48 UTC, baldersheim commented
I all good, closing until related issue reappear. Do not fix what is not broken.

2019-08-22 06:48 UTC, closed without merging