Add /loadbalancers/v1/
vespa-engine/vespa pull request #8088
Opened 2019-01-10 12:46 UTC by mpolden

2019-01-10 14:05 UTC, tokle requested changes

2019-01-10 14:18 UTC, mpolden commented on node-repository/src/main/config/node-repository.xml
> +    <binding>http://*/loadbalancers/v1/*</binding>
It's useful for inspecting APIs on `localhost:19071`. This is the same for all config server APIs.

2019-01-10 14:18 UTC, mpolden commented on node-repository/src/main/config/node-repository.xml
> +    <binding>https://*/loadbalancers/v2/*</binding>
Thanks, will fix.

2019-01-11 12:04 UTC, tokle approved these changes

2019-01-11 12:12 UTC, merged