Maintainer updating name service for load balancers
vespa-engine/vespa pull request #8173
Opened 2019-01-16 12:39 UTC by tokle

2019-01-16 14:52 UTC, mpolden requested changes
Good start, please consider my comments.

2019-01-16 14:52 UTC, mpolden commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/LockedApplication.java
> +                                                  previousDeployment.activity(), Collections.emptyMap());
This should be `previousDeployment.loadBalancers()` so load balancers are not thrown away when updating deployments.

2019-01-16 14:52 UTC, mpolden commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/application/Deployment.java
> +        this.loadBalancers = Objects.requireNonNull(loadBalancers, "loadBalancers cannot be null");
Please wrap this with `ImmutableMap#copyOf`. The same should be done for the `clusterUtilization` and `clusterInfo` fields.

2019-01-16 14:52 UTC, mpolden commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/maintenance/ControllerMaintenance.java
> +        loadbalancerMaintainer = new LoadBalancerMaintainer(controller, Duration.ofMinutes(5), jobControl, nameService);
This should be deconstructed in the `deconstruct` method.

2019-01-16 14:52 UTC, mpolden commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/maintenance/LoadBalancerMaintainer.java
> +        Map<ZoneId, List<LoadBalancer>> applicationZoneLoadBalancers = new HashMap<>();
Consider just `zoneLoadBalancers`, application dimension is implied by method name.

2019-01-16 14:52 UTC, mpolden commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/maintenance/LoadBalancerMaintainer.java
> +                log.log(LogLevel.INFO,
Warning? Also consider adding `"Retrying in " + maintenanceInterval()` to the message.

2019-01-16 14:52 UTC, mpolden commented on controller-api/src/main/java/com/yahoo/vespa/hosted/controller/api/integration/configserver/LoadBalancer.java
> +    private final String hostname;
Type should be `com.yahoo.config.provision.HostName`.

2019-01-16 14:52 UTC, mpolden commented on controller-api/src/main/java/com/yahoo/vespa/hosted/controller/api/integration/configserver/LoadBalancer.java
> +    private final String cluster;
Type should be `com.yahoo.config.provision.ClusterSpec.Id`.

2019-01-16 14:52 UTC, mpolden commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/maintenance/LoadBalancerMaintainer.java
> +                    nameService.createCname(recordName, recordData);
As discussed offline: This should use a combination of `NameService#findRecord` and not assume that implementation of `NameService#createCname` is idempotent.

2019-01-16 14:52 UTC, mpolden commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/maintenance/LoadBalancerMaintainer.java
> +                    log.log(LogLevel.INFO,
Warning? Also consider adding `"Retrying in " + maintenanceInterval()` to the message.

2019-01-16 14:52 UTC, mpolden commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/persistence/ApplicationSerializer.java
> +        Map<ClusterSpec.Id, HostName> map = new HashMap<>();
Consider a more descriptive name.

2019-01-16 14:52 UTC, mpolden commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/maintenance/LoadBalancerMaintainer.java
> +public class LoadBalancerMaintainer extends Maintainer {
Add javadoc with a short description of what this does and author.

2019-01-16 14:52 UTC, mpolden commented on controller-server/src/test/java/com/yahoo/vespa/hosted/controller/maintenance/LoadBalancerMaintainerTest.java
> + * @author mpolden
Is this for plausible deniability? 🙂

2019-01-16 14:52 UTC, mpolden commented on controller-api/src/main/java/com/yahoo/vespa/hosted/controller/api/integration/configserver/LoadBalancer.java
> +public class LoadBalancer {
Add javadoc with short description and author.

2019-01-24 14:44 UTC, tokle commented
@andreer fyi

2019-01-25 07:46 UTC, mpolden commented on controller-server/src/test/java/com/yahoo/vespa/hosted/controller/persistence/LoadBalancerNameSerializerTest.java
> +        });
Missing asserts?

2019-01-25 07:46 UTC, mpolden commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/persistence/LoadBalancerNameSerializer.java
> +//        return Collections.unmodifiableSet(osVersions);
Remove?

2019-01-25 08:01 UTC, mpolden approved these changes

2019-01-25 14:29 UTC, merged