enable manually redeploying without specifying versions
vespa-engine/vespa pull request #8188
Opened 2019-01-17 15:25 UTC by andreer

2019-01-17 15:39 UTC, jonmv commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/restapi/application/ApplicationApiHandler.java
> +            applicationVersion = Optional.ofNullable(deployment.get().applicationVersion());
`.applicationVersion()` never returns `null`. What you want to check for is whether it's `ApplicationVersion.unknown`.

2019-01-17 15:42 UTC, jonmv commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/restapi/application/ApplicationApiHandler.java
> +            vespaVersion = Optional.ofNullable(deployment.get().version());
Also never `null`.

2019-01-17 15:43 UTC, jonmv requested changes
One little thing to fix, but looks good otherwise.

Of course, it leaves even more mess — hopefully enough to make me clean it all up soon ┏( ﾟ益ﾟ)ゞ

2019-01-18 12:53 UTC, jonmv approved these changes
(╭ರ_•́)

2019-01-25 13:48 UTC, mpolden commented
Merge?

2019-01-25 13:55 UTC, merged

2019-01-28 07:56 UTC, andreer commented
Yes, thank you.