nested namepace and related cleanup
vespa-engine/vespa pull request #8204
Opened 2019-01-22 12:20 UTC by baldersheim

@havardpe PR
No semantic changes

2019-01-22 13:00 UTC, havardpe requested changes
please revert the auto-formatting performed on searchlib/src/vespa/searchlib/features/element_similarity_feature.cpp

2019-01-22 14:31 UTC, baldersheim commented
@havardpe Fixed

2019-01-22 15:02 UTC, havardpe reviewed
some minor comments

2019-01-22 15:02 UTC, havardpe commented on searchlib/src/vespa/searchlib/features/element_similarity_feature.cpp
> +ElementSimilarityBlueprint::createExecutor(const fef::IQueryEnvironment &env, vespalib::Stash &stash) const {
class functions should have open-brace on separate line

2019-01-22 15:09 UTC, vekterli commented on searchlib/src/vespa/searchlib/features/dotproductfeature.h
> +    ~SparseDotProductByContentFillExecutor() override;
`override` is preferred on destructors of child types in hierarchies containing virtual functions, as its enforces that the parent has implemented a virtual destructor. I.e. no sneaky resource leaks. Compilers will often warn on this (no-virtual-dtor etc), but good to not have to depend on this.

2019-01-23 08:22 UTC, baldersheim commented on searchlib/src/vespa/searchlib/features/element_similarity_feature.cpp
> +            (!field.isFilter())) {
I do too, fixed

2019-01-23 08:22 UTC, baldersheim commented on searchlib/src/vespa/searchlib/features/dotproductfeature.h
> +    ~DotProductBlueprint() override;
See above.

2019-01-24 08:22 UTC, merged