Jvenstad/contain zms zts et al
vespa-engine/vespa pull request #8775
Opened 2019-03-13 12:30 UTC by jonmv

@tokle FYI.

2019-03-15 21:11 UTC, jonmv commented
@tokle tests pass now. Take a look if you want. Otherwise, I can try to split into smaller commit first, but it won't be easy >_<

2019-03-18 07:14 UTC, jonmv commented
We also need to set up the new component in controller services.

2019-03-18 08:01 UTC, jonmv commented
Moved things to facilitate component setup, and added some more scaffolding for you to fill out.

2019-03-18 09:20 UTC, tokle requested changes

2019-03-18 09:20 UTC, tokle commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/TenantController.java
> +    private final PermitStore permits;
What we really create here are roles. We should consider a different name

AccessControlBackend ?

2019-03-18 11:55 UTC, jonmv commented on controller-server/src/test/java/com/yahoo/vespa/hosted/controller/restapi/ContainerControllerTester.java
> +        domain.admin(AthenzIdentities.from(new AthenzDomain("user"), userName));
Done.

2019-03-18 11:57 UTC, jonmv commented on controller-server/src/main/java/com/yahoo/vespa/hosted/controller/ApplicationController.java
> +    public Application createApplication(ApplicationId id, Optional<ApplicationPermit> permit) {
Ah, but the application thing also contains the principal creating the application, which shall be the first admin for the `Cloud`s, while the `Athenz` one doesn't have this. So we're on `Spec` again, I think.

2019-03-18 11:58 UTC, jonmv commented
Do you mind if I merge this now to see if it works, and then rename things later?

2019-03-18 12:37 UTC, tokle approved these changes

2019-03-18 12:41 UTC, merged