Geirst/logd implement rpc forwarder
vespa-engine/vespa pull request #8937
Opened 2019-03-28 11:51 UTC by geirst

@toregge please review
@havardpe please review first commit (containing rpc integration)
@bjorncs FYI

2019-03-28 14:24 UTC, havardpe commented on logd/src/logd/rpc_forwarder.cpp
> +      _supervisor(),
consider keeping the supervisor external to enable re-connect without having to re-create 'the world'

2019-03-28 14:24 UTC, havardpe commented on logd/src/logd/rpc_forwarder.cpp
> +    request->SubRef();
consider using request subref guard

2019-03-28 19:22 UTC, toregge requested changes
Looks mostly ok, but need to add all methods before starting the supervisor, as mentioned by @havardpe

2019-03-29 08:47 UTC, geirst commented
@toregge PTAL

2019-03-29 09:39 UTC, toregge approved these changes

2019-03-29 09:43 UTC, merged