parse (and ignore for now) tensor cell type in tensor type spec
vespa-engine/vespa pull request #9029
Opened 2019-04-05 10:17 UTC by havardpe

example: tensor<float>(x[10])

@arnej27959 please review

2019-04-05 15:54 UTC, baldersheim requested changes
eval_node_types_test_app not too happy.

2019-04-08 10:32 UTC, havardpe commented
test should be more happy now

2019-04-08 13:05 UTC, arnej27959 approved these changes
looks good to me

2019-04-08 13:24 UTC, baldersheim approved these changes

2019-04-08 13:24 UTC, merged